### ISSUE TITLE
Add Batch support

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/setapdfsigner-ais#5]
There must be an option provided by SetaSign in order to sign multiple documents/PDFs with one AIS request containing the Batch elements

**Comment by Setasign** [comment]
We implemented an asyncron signature creation process in the upcoming release of the SetaPDF-Signer component:
```
// 1. prepare the PDF document with the signature gap and correct byte offset values
$tmpDocument = $signer->preSign(new SetaPDF_Core_Writer_TempFile());
$module = new SetaPDF_Signer_Signature_Module_AIS();
// ...
// 2. create a signature by the tmpDocument and the module (the logic of createSignature() can also be done outsite of the Signer instance/class
$signature = $signer->createSignature($tmpDocument, $module);
// 3. place the signature into the $tmpDocument instance and save it
$signer->saveSignature($tmpDocument, $signature);
```
The SetaPDF_Signer_TmpDocument instance returned by preSign() is also serializeable, so it can be saved e.g. in a session (anyhow in that case you need to provide a File writer, because the TempFile class will delete the temporary file when it is descructed.).

It's only step 2 that needs to be replaced by a "batch" process.

**Comment by FreddyKaiser** [comment]
Done with https://github.com/Setasign/SetaPDF-Signer-Addon-SwisscomAIS
